require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Market::SitesController do

  # This should return the minimal set of attributes required to create a valid
  # Market::Site. As you add validations to Market::Site, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Market::SitesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all market_sites as @market_sites" do
      site = Market::Site.create! valid_attributes
      get :index, {}, valid_session
      assigns(:market_sites).should eq([site])
    end
  end

  describe "GET show" do
    it "assigns the requested market_site as @market_site" do
      site = Market::Site.create! valid_attributes
      get :show, {:id => site.to_param}, valid_session
      assigns(:market_site).should eq(site)
    end
  end

  describe "GET new" do
    it "assigns a new market_site as @market_site" do
      get :new, {}, valid_session
      assigns(:market_site).should be_a_new(Market::Site)
    end
  end

  describe "GET edit" do
    it "assigns the requested market_site as @market_site" do
      site = Market::Site.create! valid_attributes
      get :edit, {:id => site.to_param}, valid_session
      assigns(:market_site).should eq(site)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Market::Site" do
        expect {
          post :create, {:market_site => valid_attributes}, valid_session
        }.to change(Market::Site, :count).by(1)
      end

      it "assigns a newly created market_site as @market_site" do
        post :create, {:market_site => valid_attributes}, valid_session
        assigns(:market_site).should be_a(Market::Site)
        assigns(:market_site).should be_persisted
      end

      it "redirects to the created market_site" do
        post :create, {:market_site => valid_attributes}, valid_session
        response.should redirect_to(Market::Site.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved market_site as @market_site" do
        # Trigger the behavior that occurs when invalid params are submitted
        Market::Site.any_instance.stub(:save).and_return(false)
        post :create, {:market_site => { "name" => "invalid value" }}, valid_session
        assigns(:market_site).should be_a_new(Market::Site)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Market::Site.any_instance.stub(:save).and_return(false)
        post :create, {:market_site => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested market_site" do
        site = Market::Site.create! valid_attributes
        # Assuming there are no other market_sites in the database, this
        # specifies that the Market::Site created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Market::Site.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => site.to_param, :market_site => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested market_site as @market_site" do
        site = Market::Site.create! valid_attributes
        put :update, {:id => site.to_param, :market_site => valid_attributes}, valid_session
        assigns(:market_site).should eq(site)
      end

      it "redirects to the market_site" do
        site = Market::Site.create! valid_attributes
        put :update, {:id => site.to_param, :market_site => valid_attributes}, valid_session
        response.should redirect_to(site)
      end
    end

    describe "with invalid params" do
      it "assigns the market_site as @market_site" do
        site = Market::Site.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Market::Site.any_instance.stub(:save).and_return(false)
        put :update, {:id => site.to_param, :market_site => { "name" => "invalid value" }}, valid_session
        assigns(:market_site).should eq(site)
      end

      it "re-renders the 'edit' template" do
        site = Market::Site.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Market::Site.any_instance.stub(:save).and_return(false)
        put :update, {:id => site.to_param, :market_site => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested market_site" do
      site = Market::Site.create! valid_attributes
      expect {
        delete :destroy, {:id => site.to_param}, valid_session
      }.to change(Market::Site, :count).by(-1)
    end

    it "redirects to the market_sites list" do
      site = Market::Site.create! valid_attributes
      delete :destroy, {:id => site.to_param}, valid_session
      response.should redirect_to(market_sites_url)
    end
  end

end
