require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Market::TodoItemsController do

  # This should return the minimal set of attributes required to create a valid
  # Market::TodoItem. As you add validations to Market::TodoItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "site" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Market::TodoItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all market_todo_items as @market_todo_items" do
      todo_item = Market::TodoItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:market_todo_items).should eq([todo_item])
    end
  end

  describe "GET show" do
    it "assigns the requested market_todo_item as @market_todo_item" do
      todo_item = Market::TodoItem.create! valid_attributes
      get :show, {:id => todo_item.to_param}, valid_session
      assigns(:market_todo_item).should eq(todo_item)
    end
  end

  describe "GET new" do
    it "assigns a new market_todo_item as @market_todo_item" do
      get :new, {}, valid_session
      assigns(:market_todo_item).should be_a_new(Market::TodoItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested market_todo_item as @market_todo_item" do
      todo_item = Market::TodoItem.create! valid_attributes
      get :edit, {:id => todo_item.to_param}, valid_session
      assigns(:market_todo_item).should eq(todo_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Market::TodoItem" do
        expect {
          post :create, {:market_todo_item => valid_attributes}, valid_session
        }.to change(Market::TodoItem, :count).by(1)
      end

      it "assigns a newly created market_todo_item as @market_todo_item" do
        post :create, {:market_todo_item => valid_attributes}, valid_session
        assigns(:market_todo_item).should be_a(Market::TodoItem)
        assigns(:market_todo_item).should be_persisted
      end

      it "redirects to the created market_todo_item" do
        post :create, {:market_todo_item => valid_attributes}, valid_session
        response.should redirect_to(Market::TodoItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved market_todo_item as @market_todo_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        Market::TodoItem.any_instance.stub(:save).and_return(false)
        post :create, {:market_todo_item => { "site" => "invalid value" }}, valid_session
        assigns(:market_todo_item).should be_a_new(Market::TodoItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Market::TodoItem.any_instance.stub(:save).and_return(false)
        post :create, {:market_todo_item => { "site" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested market_todo_item" do
        todo_item = Market::TodoItem.create! valid_attributes
        # Assuming there are no other market_todo_items in the database, this
        # specifies that the Market::TodoItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Market::TodoItem.any_instance.should_receive(:update).with({ "site" => "" })
        put :update, {:id => todo_item.to_param, :market_todo_item => { "site" => "" }}, valid_session
      end

      it "assigns the requested market_todo_item as @market_todo_item" do
        todo_item = Market::TodoItem.create! valid_attributes
        put :update, {:id => todo_item.to_param, :market_todo_item => valid_attributes}, valid_session
        assigns(:market_todo_item).should eq(todo_item)
      end

      it "redirects to the market_todo_item" do
        todo_item = Market::TodoItem.create! valid_attributes
        put :update, {:id => todo_item.to_param, :market_todo_item => valid_attributes}, valid_session
        response.should redirect_to(todo_item)
      end
    end

    describe "with invalid params" do
      it "assigns the market_todo_item as @market_todo_item" do
        todo_item = Market::TodoItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Market::TodoItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => todo_item.to_param, :market_todo_item => { "site" => "invalid value" }}, valid_session
        assigns(:market_todo_item).should eq(todo_item)
      end

      it "re-renders the 'edit' template" do
        todo_item = Market::TodoItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Market::TodoItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => todo_item.to_param, :market_todo_item => { "site" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested market_todo_item" do
      todo_item = Market::TodoItem.create! valid_attributes
      expect {
        delete :destroy, {:id => todo_item.to_param}, valid_session
      }.to change(Market::TodoItem, :count).by(-1)
    end

    it "redirects to the market_todo_items list" do
      todo_item = Market::TodoItem.create! valid_attributes
      delete :destroy, {:id => todo_item.to_param}, valid_session
      response.should redirect_to(market_todo_items_url)
    end
  end

end
